_target_: src.models.ddsp_module.DDSP

n_harmonics: 180
n_filters: 195
in_ch: 1
out_ch: 2
reverb_dur: 3
mlp_units: 512
mlp_layers: 3
gru_units: 512
gru_layers: 3
lr: 0.0001
weight_decay: 0.001
transformer_units: 512
transformer_hidden: 512
transformer_heads: 2
transformer_layers: 3
controller: "gru"
