_target_: src.datamodules.ddsp_datamodule.DDSPDataModule

data_path: ${paths.data_dir}/cello_samples.pth
wav_dir: /home/kureta/Music/Cello Samples
example_duration: 5
example_hop_length: 1
train_val_test_split: [0.85, 0.05, 0.10]
batch_size: 8
num_workers: 8
pin_memory: True
