# @package _global_

# overfits to 3 batches

defaults:
  - default.yaml

trainer:
  max_epochs: 8
  overfit_batches: 3
  accelerator: gpu

# model ckpt and early stopping need to be disabled during overfitting
callbacks: null
